### PR TITLE
Touch Friendly UI For Main Logger UI

### PR DESCRIPTION
**Pull request by DaBlackMamba**
I added a new command param for the logger (-logger.touch) that just sets a private Boolean.  This is then used to change a number of the Main Logger UI components so that it's a lot more touch friendly.  Not very useful on a laptop, but on a small tablet it works nice for some simple in car monitoring.

### CODE REVIEW

**Comment by dschultzca** [comment]
Hi:
Can you check that your changes will apply to my master branch cleanly as it will be merged into the RR master soon.
https://github.com/dschultzca/RomRaider
Thanks.

**Comment by DaBlackMamba** [comment]
Sure, I'll target tomorrow

**Comment by DaBlackMamba** [comment]
How about I fork your repro and make a pull request to your repro?
Seems like the easiest to manage merge stuff...

-Thx

**Comment by fredcooke** [comment]
Dale should be keeping the master repo up to date on a frequent basis. Hopefully he is. As for forking his vs forking this etc, pointless, the commit structure is the same. If he says to be up to date with his branch, keep a copy of your original and perform the rebase as instructed. If he goes and modifies it after that and leaves you dangling, he should do the work to resolve that and you're well within your rights to ask for it. Otherwise he can just pull yours in from this request with a --ff-only.

**Comment by DaBlackMamba** [comment]
@dschultzca - yep your instinct is correct.  My code change five files - 4 are clean but eculogger.java is not go figure :)

I think the simple/safe path is for your pull request to go first, then I'll do a merge in my fork and create a new pull request.  If people really want my change they can just ping me or build from my fork.

-Thx

src/main/java/com/romraider/ECUExec.java (clean)
src/main/java/com/romraider/logger/ecu/EcuLogger.java (not clean)  
src/main/java/com/romraider/logger/ecu/ui/paramlist/ParameterListTable.java (clean) 
src/main/java/com/romraider/logger/ecu/ui/paramlist/UnitsComboBoxEditor.java (clean)
src/main/java/com/romraider/logger/ecu/ui/paramlist/UnitsComboBoxRenderer.java (clean)

**Comment by DaBlackMamba** [comment]
@fredcooke - Yep I agree but I think it's good to be flexible about conflicts in files like eculogger.java.  I think the goal should be that the main branch works with both updates putting ordering and time aside.

-Thx

**Comment by fredcooke** [comment]
The trouble is that Dale's known for having long-lived branches that are not in the official repo. This is unhealthy behaviour in general. I didn't look this time and could be totally wrong, but that's my guess. What he should do is create a named feature branch for each thing, finish one at a time, as quickly as possible, and merge it into master when it's ready. If your pull request comes in before his then yours should get merged first and he should rebase his work ontop of it. Last in, most work resolving conflict. And by merged I mean fast forwarded as merging is dirty and unclear at the best of times.

**Comment by dschultzca** [comment]
As stated by DaBlackMamba
>src/main/java/com/romraider/logger/ecu/EcuLogger.java (not clean)
> 

I can see how that could be as the case as there have been quite a few updates here to support additional logging protocols by me and others.

**Comment by dschultzca** [comment]
Have a look at this branch for your changes: https://github.com/dschultzca/RomRaider/tree/touch
I squashed your two commits into one which made it much easier to resolve the conflicts in EcuLogger.java.  I had to back out your parameterization since Java 6 JDK doesn't support that.
If you can test it and all is good I'll move it to the master.

**Comment by DaBlackMamba** [comment]
Thanks -
Looks like I was sloppy with whitespace/formatting?  Do you want me to fix and make a pull request today?  Other than that it look fine.

**Comment by dschultzca** [comment]
I'm not sure what you mean as I don't see any problems in the commit difference.
If it's working, no need to make a new request your changes will be merged into the master branch from my test branch.

**Comment by DaBlackMamba** [comment]
It's working fine - I just have some tabs rather than spaces in some locations.
Not sure how much this project gets concerned about this type of small formatting issue.
  
https://github.com/dschultzca/RomRaider/commit/d5108389f87bf4e4d97d2a801cbe26f9e00eda2d
I can always fix it with another pull request if needed.

-Thx

**Comment by dschultzca** [comment]
OK now I see what you mean.  If you wish to fix the blank lines with spaces and tabs as well as the trailing spaces and tabs then go ahead.
Personally I use 4 spaces in place of a tab since I don't use a wide screen display this keeps most of the text within the view area of the screen without having to scroll right/left all the time to read a line of code.

**Comment by fredcooke** [comment]
Whitespace is not a personal thing, it's a per-project thing, unless you want a complete shambles. 

As for using spaces instead of tabs because of screen realestate, this shows that either you use exceptionally poor tooling, or don't know how to use your tooling. Tabs entire purpose in life is to produce variable indentation with one tab specifying one indentation, but not specifying how far an indentation is on the screen.

All post content spacing should be done with spaces otherwise varying tab size will cause misalignments of trailing comments on the same indentation level with different lengths of content beneath them.

**Comment by dschultzca** [comment]
I have my IDE configured for tab= width 4.
How do you get GitHub or a browser to display the same?
Right now the project is using spaces for all indentation.

**Comment by dschultzca** [comment]
Added in commit d5108389f87bf4e4d97d2a801cbe26f9e00eda2d

**Pull request closed without merging**
