### PR TITLE
XDF Support and Automatic To_Byte Alternative

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
this PR adds support for XDF files generated by TunerPro. There is still some things to do here, but its mostly working as it should. XDFs dont have a to_byte function, so I added an approximation method which gets used automatically if no to_byte function is supplied. In the future one could create a syntax tree and sort of do the math based on the supplied string the same way you would do on paper. XDFs also dont have an identification part, so if an xdf is put in the definition picker it will always be chosen if no previous definition is found. I added a warning popup for this. Once an XDF is loaded you can save it as a RR definition (under file) and manually add the identification part.

The tables and categories are also sorted now, while categories are always at the top. Axis are also now treated as a normal Table1D type, since its only the GUI thats different.

Cheers,
Robin

### CODE REVIEW

**Comment by dschultzca** [comment]
You'll have to sync your branch up to the master branch before it can be merged.

**Comment by dschultzca** [comment]
Your latest merge did not rebase your changes onto the current master, can you try again?

**Comment by GTO2013** [comment]
I tried a rebase before, but it failed with random merge conflicts that didn't make sense to me... Is it not possible to merge currently?

**Comment by GTO2013** [comment]
Thanks for the merge, I will try to rebase it next time!

**Pull request merged**
