### PR TITLE
better state validation

### PR DESCRIPTION
**Pull request by rusefi**
would you be guys interested in better internal state validation?

### CODE REVIEW

**Comment by dschultzca** [comment]
Can you describe a problem case this will fix?

**Comment by rusefi** [comment]
Problem: invalid rom file definition breaks internal constraint. In order to simplify troubleshooting, I suggest changing error handling pattern and adopting http://en.wikipedia.org/wiki/Defensive_programming approach. These checks while a drop in the bucket would get the ball rolling :)

**Comment by dschultzca** [comment]
Please review this branch to see if there have been code changes in this area.
https://github.com/dschultzca/RomRaider/tree/master
If not then we can look at your suggestions.

**Comment by rusefi** [comment]
Same change could and should be applied to https://github.com/dschultzca/RomRaider/tree/master

**Comment by dschultzca** [comment]
What kind of "invalid rom file definition breaks internal constraint." caused the issue you are fixing?
Can you provide an example?

**Comment by rusefi** [comment]
Table3D change was my mistake, these fields are never null

I still believe that RomTree is a good change - it is checking for a null condition which happens if you click below a short list of tables.

I need to learn how to put separate changes into separate pull requests :)

**Comment by dschultzca** [comment]
OK thanks.

**Comment by dschultzca** [comment]
I pulled in your RomTree change, commit cf800db7969c996e9fbb62bbe979ff9cdc19efd0

**Pull request closed without merging**
