### PR TITLE
removing unneeded NPE handing, minor code formatting

### PR DESCRIPTION
**Pull request by rusefi**
With all the recent not-null checks I believe NPE handling is not needed any more

exceptions should only be used for exceptional situations - that's not the case here

### CODE REVIEW

**Comment by rusefi** [comment]
Poke :)

**Comment by dschultzca** [comment]
I'll try to get to it this week, assuming I can get my computer monitor fixed. I have a few other Logger updates to test and push up too.

**Comment by dschultzca** [comment]
commit 8a1e84413d7f504fbe97e972c6215fad8c858292 and c1a20c3aac55ceef0d5c5dffdce001176f3aa67b
If you don't mind in the future to bump the copyright date in the files you modify, thanks.

**Comment by rusefi** [comment]
Will do re: copyright date

**Pull request closed without merging**
