### PR TITLE
GitHub action to build RR

### PR DESCRIPTION
**Pull request by rusefillc**
GitHub action to build RR

### CODE REVIEW

**Comment by dschultzca** [comment]
What is the purpose of this action?

**Comment by rusefillc** [comment]
As is it would assert that master and future PRs build successfully on each merge

in the future it could be adjusted to preserve artifacts to have binaries on each merge automatically

**Comment by dschultzca** [comment]
What information would this provide?
Doing a build in a Linux environment does not create all the assets that a build on a dedicate Windows dev system provides.  Linux can not build the Windows installation files.  So this would only compile and assemble some jars.
Also, the unit tests would fail as the unit test jars are not been installed.

**Comment by rusefillc** [comment]
at the moment it has provided information that "ant all" does NOT fail on linux. If in your opinion it was supposed to fail on Linux  - well now you know that it did not fail as expected - please go over https://github.com/rusefi/RomRaider/runs/5369737640?check_suite_focus=true output when you have a chance

github actions have Windows runners if so desired. please let me know if I shall switch build to Windows. but again - at the moment it does not fail, maybe first step is to merge

second step to fix it so that it FAILS on linux

and then third step switch to Windows to see not failing again?

**Comment by dschultzca** [comment]
My mistake.  I assumed building on Linux ran the unit tests under the compile-linux target, but it does not.  

I see the Windows products did not build at:  
https://github.com/rusefi/RomRaider/runs/5369737640?check_suite_focus=true#step:6:87  
This will only work in a Windows build environment.

How do you get 32bit products from this?

**Comment by rusefillc** [comment]
https://github.com/RomRaider/RomRaider/issues/163 created

**Comment by rusefillc** [comment]
@dschultzca poke.

Please either reject this PR if you would like to clearly state that RomRaider insists on manual build and rejects automation or continues integration which seem to be pretty widely in the software development industry these days.

Otherwise please state what changes are needed in order to merge this PR which in my opinion, well, provides some value at least by giving all future pull requests a clear build passed / build failed icon.

**Comment by GTO2013** [comment]
I have built on your PR and added a way to get the build artefact, it should be linked above

**Comment by rusefillc** [comment]
@GTO2013 it looks like at the moment I am failing to convince repo maintainer of the benefits of github actions, any chance you could add any arguments?

**Comment by dschultzca** [comment]
To be honest, I forgot about this.  At the moment I don't have much time to contribute to RomRaider.  Hopefully I can find some time over the next couple of months.  So leave it with me.

**Comment by rusefillc** [comment]
@dschultzca I am so confused, any chance you can help me understand your context? What is your hesitation with this PR which just adds a new file? How is this different from for instance https://github.com/RomRaider/RomRaider/pull/201/commits/96a4a6bb55835772ef179844de82bcaf2aa19a94?

* Do you see a risk that any of the existing workflows would be broken? Hopefully not.
* Do you see a security risk of any sort? Hopefully not.

I bet you've noticed that multiple people are trying to build on top of this PR, that looks like a signal that a few of the developers see the potential here, including @GTO2013 who is a very active collaborator. Would not it make sense to see a good risk/benefit and not block progress for the next couple of months?

**Comment by dschultzca** [comment]
Can you review the build action to make sure it still completes successfully?

**Comment by rusefillc** [comment]
Had to rebase and update the task it's now green, ready to be merged

https://github.com/rusefi/RomRaider/actions/runs/3519343349

**Pull request merged**
