### PR TITLE
TTS Removal and Repo Cleanup

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
this PR changes the following:

- Replace TTS with a warning sound file
- Switch to Java 11 (Reverted)
- Fix of the run.bat and run.sh, they didnt work in the installation folder
- Removal of definition files for installation
- Moved definition files in seperate folder
- Moved documents in doc folder
- Move log4j properties in lib folder
- Set source option in installer to default false

You need to update Launch4J locally, I didnt want to push this in the repo (creates a giant diff)

Cheers!

### CODE REVIEW

**Comment by dschultzca** [comment]
That's a lot of changes in one PR.

**Comment by dschultzca** [comment]
Oops, clicked the wrong spot on the page.

**Comment by GTO2013** [comment]
It might seem more than it looks, but most of the diff is just moving files. I did these changes in maybe 3 hours or so

**Comment by dschultzca** [comment]
I was hoping to do another release before making changes that require users to upgrade their Java version.  Can we hold these for now?

**Comment by dschultzca** [comment]
Your commit seems to update lunch4j, I was thinking to remove it completely.

**Comment by GTO2013** [comment]
Sure just leave the PR open. Or you could create a new branch (java11-switch for example) and I could set the target branch for this PR to that branch. There are still some ancient branches in the repo (0.2.0) by the way

**Comment by dschultzca** [comment]
Ah, I see what happen.  That's quite a mess, can you squash these into a couple of commits?

**Comment by GTO2013** [comment]
Or I just remove the Java 11 switch and keep the rest?

**Comment by GTO2013** [comment]
I squashed the commits and reverted the Java 11 switch

**Comment by dschultzca** [comment]
Can you move the run.bat and run.sh files back to the root dir.  These are the launch scripts for the standalone RomRaider implementation.  These should be evident to the user. In the scripts directory they will not work to launch RR.

**Comment by dschultzca** [comment]
Also need to fix Logger profiles not loading:  
```
java.io.FileNotFoundException: RomRaider\profile.dtd (The system cannot find the file specified)
	at com.romraider.logger.ecu.profile.UserProfileLoaderImpl.loadProfile(UserProfileLoaderImpl.java:42)
```

**Comment by GTO2013** [comment]
The installer will place the run.bat or run.sh in the root folder during installation and in the standalone zip, should be correct then?
Is it fine if I just remove the link to the profile.dtd in the xml generator? The xml is generated automatically and does not get updated by hand usually. Looking at the last time the other dtd files were touched I dont think these are up to data any longer. Might be better to invest more time in the instructions for custom definitions on the website instead?

**Comment by dschultzca** [comment]
The installers do nothing with the run.* files as they are only used in the standalone ZIP distribution.  When Zipped these need to be in the root of the RomRaider archive.  

I guess if we have appropriate checks while reading in a profile XML file in we could do away with the DTD.  True it is rarely ever modified by a regular user.

**Comment by dschultzca** [comment]
Just removing the DTD line from being written into the profile XML is not going to work for the users.  Every profile ever created has the profile.dtd file name embedded in them.  So you can't open an existing profile without the profile.dtd file in the base directory.  We will need to find a better way to drop this requirement.  

The run.* files are still in the script dir and need to be moved back, plus they need to be the files from my commit 3edc87c4.

**Comment by GTO2013** [comment]
I implemented a patch function in the UserProfileLoader, it will remove the dtd line in the xml. Regarding the run files I think we are talking past each other, or I am misunderstanding something. I have updated the build script to move the run file from scripts/run.xx into the root folder for the zip. So it will work in the standalone zip, but not in from the repo. But you dont need to ever run the run scripts from the repo, or do you? I have reverted the changes back in the run files. I got confused, because the lib path in the installation does not contain 32 or 64, but it does in the standalone zip. Is this intended?

**Comment by dschultzca** [comment]
I may have missed the fact that when creating the ZIPs the build script moved the run.* files to the root.  That's all that is needed to make the standalone installation work.  
The standalones are basically just zips of the repo with little directory structure change, so we need to keep the libs path pointing to the correct bitness directory.   I was planning to introduce run64.* files for when we are ready for that release.

For the install packages I adjusted the scripts to move the 32bit files up one directory so that the package is tailored to the 32 bit environment.  This should also work correctly for a 64bit build package (when we get there).

**Comment by GTO2013** [comment]
I see, thanks!

**Pull request merged**
