### PR TITLE
Bosch Axis Substract Layout

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
this should implement #92 from Thread:  https://www.romraider.com/forum/viewtopic.php?t=16613
Test files can be taken from here: https://github.com/ba114/M5.2.1

To make this work all you have to do is add an attribute <table ... substractLayout="true" />, which I set for the right table in the image:

bosch_working

I have tested loading and saving successfully, let me know if I missed something!

### CODE REVIEW

**Comment by GTO2013** [comment]
I just figured out something really cool I didnt even know worked:: In some older commit I mentioned that i enabled x-include in xml files. So you can link other files and include them. That also works for http links! 

<?xml version="1.0" encoding="utf-8"?>

<xi:include href="https://raw.githubusercontent.com/ba114/M5.2.1/master/M5.2.1%20ECU%20Definitions%20v0.0.1.xml" xmlns:xi="http://www.w3.org/2001/XInclude"></xi:include>

That definition is all you need to link to the ME github definition, will automatically update! You just need an internet connection of course.

**Comment by dschultzca** [comment]
I found a decent [reference for xinclude here](https://www.xml.com/pub/a/2002/07/31/xinclude.html).  It documents what you discovered and how to handle broken connections.

**Comment by GTO2013** [comment]
Yeah, you could include the local file as a fallback. Or you could just add the local file as a second definition with a lower priority. I will create a separate pull request for that though, because currently if a file fails to parse it does not continue to check the other definitions.

**Comment by dschultzca** [comment]
Your change committed in 8e3b42bebfc530b397bf0b258251a1c1eae49aac.
Will you be updating the thread on the forum with instructions on how to use the new axis table attribute?

**Comment by GTO2013** [comment]
Sure, I can update the thread. Is there any documentation for creating ECU/logging definitions in one place? The FAQ on the website is more aimed towards users, not people who want to create definitions.  I think adding some documentation on the wiki github page will be helpful for many people, we just have to make sure the users know about it :)

**Comment by dschultzca** [comment]
We can add a section to the RomRaider Wiki for definition development.  That way any RomRaider user can contribute/update the content including uploading samples and images.

**Pull request closed without merging**
