### PR TITLE
Editor / Logger connection and new release?

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
this should improve the connection between the Editor and the Logger. Previously you had to start the Editor first and then launch the Logger within the Editor. You should now be able to start them in which order you like and the log overlay should work. I tested the log overlay in my BMW, maybe you can test it a bit further in your Subaru.

If this looks good I think it would be a good point for a new release? Last release was one year ago, so I dont think it would hurt to give the majority of the users access to the fixes and new features. If there are any problems I can fix them on this branch.

Edit: I also allowed multi-selection in the openImage dialog, forgot to mention that!

Cheers!

### CODE REVIEW

**Comment by Pytrex** [comment]
Great job! I definitely agree with the idea of pushing out a new release! Been waiting for it before I push my new definition repo with the updated template haha But I know that dschultz is working on Nissan CAN logging support, so he might be wanting to wait until that's finished to push a new release.

**Comment by dschultzca** [comment]
I see the Launch Logger option is missing from the Editor menu, did you mean to do that?  I find it quite handy.

**Comment by GTO2013** [comment]
I thought it was just added to solve the problem of opening it within the same application, I just commented out the part where it gets added to the menu. Could also be easily added back in in another PR

**Comment by dschultzca** [comment]
For me, it's one click to open the Logger as opposed to hunting through Windows menus system again.  If you prefer to leave out that's fine.
I also see a few updated files that didn't get a date bump.

**Comment by dschultzca** [comment]
New release is published.

**Pull request merged**
