### PR TITLE
Add containerized unittest and build

### PR DESCRIPTION
**Pull request by sarahbx**
First pass at containerized unit tests to build against a known environment.
If unit tests pass, will recompile linux jar without test files.
Usage:
`podman build -t romraider .`
or
`docker build -t romraider .`

### CODE REVIEW

**Comment by fredcooke** [comment]
Great work, Sarah. This is without a doubt the only way to go. Let's hope the old fashioned people don't object as this is a big step in the right direction IMO.

**Comment by fredcooke** [comment]
PS, so weird to see a github PR without CI build results/statuses above the merge button!

**Comment by sarahbx** [comment]
ty @fredcooke, hoping this will help with migration to newer libraries and more unit testing. I'm interested in this project for personal reasons, and would hate to break the wrx. :sunglasses:

**Comment by fredcooke** [comment]
Ha ha, unless you have a 6-speed STI it's certain to break 2nd gear at some point anyway :-D No idea how those tiny rear diffs survive unless it's through centre diff/link slip to unload/soften the rear forces. Big ends are tiny, too, but you probably know that :-D I'd say the biggest risk to those components is that you're tuning it implying power upgrades ;-)

**Comment by dschultzca** [comment]
Hi Sarah:
Thanks for your contribution.  RomRaider still has some dependencies on libraries that are dependent on a 32bit system.  How can we manage that inside the image?

**Comment by dschultzca** [comment]
Accepted as commit 8f190f585146287cfc5512a25cd3dde3d712ee46

**Pull request closed without merging**
