### PR TITLE
Fix for Copying/Pasting and Setting values for Table2D

### LINKED ISSUE #117: Editor - Sometimes Forced to Hit "Set" in order to Set an Axis Value
Sometimes (primarily with tables, rather than maps), certain tables won't let you enter new values into the axis. You can highlight the axis, but hitting enter won't update the values to whatever you want to set them to. But by hitting "set", it properly sets the value. This happens with scalings and raw values, so I don't think the scaling has any impact.

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
this fixes #117 and #110. I also noticed a bug where the values were pasted in reverse if you selected the same area in a different direction. I also removed the threading code for copying, since you shouldnt really need that to copy a few strings around. The fix for #110 is a bit wierd, it seems like you need to add a short sleep before you can set it. Maybe there is a cleaner solution for this, but I havent found any problems with this approach.

If you find any new bugs let me know!

Edit: I also replaced the hardcoded JDK path with the JAVA_HOME environment variable. Builds fine for me using AdoptOpenJDK.

### CODE REVIEW

**Comment by dschultzca** [comment]
Hi:
Can you revert the 'Replaced hardcoded path with env variable f070ace' change please or use a different variable name so it doesn't conflict with the JAVA_HOME that may be set for a completely different Java installation than to one compiling RomRaider against?
Thanks

**Comment by dschultzca** [comment]
Can you also test against the multi-scale definition?  For example, 'Target Boost Compensation (ECT)' should have Metric / Standard and Raw scaling to select from.
It seems like the axis labels are not switching with the scaling selection.
[ecu_defs-multi.zip](https://github.com/RomRaider/RomRaider/files/7247822/ecu_defs-multi.zip)

**Comment by dschultzca** [comment]
See Cross-Compilation Options options at https://docs.oracle.com/javase/8//docs/technotes/tools/unix/javac.html
Unless I misunderstand, when you specify a target version, I believe the compiler expects to find an rt.jar, etc. of that version in the bootclasspath specified.

**Comment by GTO2013** [comment]
Ah I see, makes sense!

**Comment by GTO2013** [comment]
I fixed some additional bugs found by pytrex and also added the improved error feedback for loading logger definitions (for the logger.dtd issue)

**Pull request merged**
