### PR TITLE
Improving user input and multiply bug

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
while I used RR I noticed a bug when multiplying negative values, you can find the thread here:
http://www.romraider.com/forum/viewtopic.php?f=5&t=13789
It now uses the real representation, instead of the raw value.

I also restricted the user input for the set/multiply fields, so that they don't even allow invalid input while typing. If you type in an invalid value in the current version, the cell gets set to 0 most of the time. Commas also get converted to dots by default now.

### CODE REVIEW

**Comment by dschultzca** [comment]
Hi:
For the files you modified can you bump the date to the current year in the copyright notice and for the new file can you add the copyright notice?
Thanks

**Comment by GTO2013** [comment]
I updated the copyright headers. The table classes also use the raw and normal multiply function based on the current scale now.

**Comment by dschultzca** [comment]
The feature to check for invalid input causes a number entered as .25 to be converted to 25
The leading decimal seems to get stripped if you have highlight the current contents of the field and start typing with a period.  Can you fix this?

**Comment by GTO2013** [comment]
I fixed the bug you mentioned dschultzca. The multiply logic is now reversed like scotthew suggested, I only work on MS41, so I didnt know about the other scales...

**Comment by dschultzca** [comment]
To test your new feature with multiple scales just modify your MS41 definition file and configure the scalings of a few tables using this format:
`   <scaling name="Metric" units="Degrees C" expression="(x*.00244140625)-40" to_byte="(x+40)/.00244140625" format="0.0" fineincrement="1" coarseincrement="5" />`
`   <scaling name="Standard" units="Degrees F" expression="x*.00439453125-40" to_byte="(x+40)/.00439453125" format="0.0" fineincrement=".1" coarseincrement="1" />
`
You can apply it to both data and axis in a table def and in the RR Editor view a table and in the scaling drop list you get the choice of the scalings to view the table data in.

**Comment by GTO2013** [comment]
I tested it and it works on different scales correctly.

**Comment by dschultzca** [comment]
Hi:
There seems to be a problem interpreting Locale based numbers.  For instance I can't enter the value 0,5 to use as a multiplier.  It converts my entry to 0.5 and then deletes the value from the field when I press the multiply button.  Similarly there's problems if I enter -0,99 and try to Set a table cell with that value.
There's a utility class com.romraider.util.NumberUtil that does Locale based conversions, maybe this could help here?

**Comment by fredcooke** [comment]
Dale, he explicitly mentioned writing the code to do exactly what you describe. I did think it sounded, umm, unportable, at the time, but nevertheless, it was explained in writing above. So it's not really a problem to be found, more a design choice to revise. Enjoy.

**Comment by dschultzca** [comment]
I was under the impression (my misunderstanding) that converting comma to period would not interfere with the Locale compatibility we have implemented over the last few updates. The feature will have to accommodate this.

**Comment by GTO2013** [comment]
I think I also found another bug concerning comma vs dot notation. When I select the non-US format (Comma as seperator), I can set values, but nothing happens on multiply. It only works with the dot notation.

**Comment by GTO2013** [comment]
The dot, comma conversion now takes into account the current locale. I also fixed the comma multiply bug which I mentioned. The ECU Editor also allows to switch between locales now (in the Settings).

**Comment by dschultzca** [comment]
I haven't reviewed the code yet, are you accessing the same Locale setting functions as the Logger uses?  You need to be careful as the Locale information also affects the Logger and the selection in the Logger is saved to the setting.xml on exit.

**Comment by GTO2013** [comment]
Yes, I am using the code from the LogFileNumberFormatAction.java: 
```
            ublic void actionPerformed(ActionEvent actionEvent) {
        try {
            if ((Boolean) getValue(SELECTED_KEY)) {
                logger.getSettings().setLocale(EN_US);
            }
            else {
                logger.getSettings().setLocale(SYSTEM_NUMFORMAT);
            }
            showMessageDialog(logger, "The Logger has been set to use the " +
                    logger.getSettings().getLocale() + " number format.\n\n" +
                    "Exit and restart the Logger to apply the new setting.",
                    "Log File Number Format Change", INFORMATION_MESSAGE);
        } catch (Exception e) {
            logger.reportError(e);
        }
    }
```

**Comment by dschultzca** [comment]
Great, thanks.
6968559495d308e205f506b6429eda6946be16b8

**Pull request closed without merging**
