### PR TITLE
float is always little endian

### PR DESCRIPTION
**Pull request by abelom**
table endian="big" does not currently work, my change contains the fix

here is a debugger screenshot before the change:
http://i.imgur.com/LggzMFJ.png
note how value is same for ENDIAN_LITTLE = 1 and for ENDIAN_BIG = 2

here is the same spot with my fix:
http://i.imgur.com/1IVS01a.png
1.2 is the expected value from my bin

### CODE REVIEW

**Comment by dschultzca** [comment]
We are aware of this problem.
http://trac.assembla.com/romraider/ticket/2
Unfortunately we can't make this correction until all ECU definitions utilizing float parameters are corrected in conjunction with the Editor change.
If you are defining float in a definition you will need to use endian="little" to get the correct data interpretation.
Is your data truly little endian?

**Comment by rusefi** [comment]
Oh, not a problem.

Yep, I really the-other-kind of endian - I am looking into using RomRaider to tune my own ECU, not a subary. Will post on the forum once I make any progress!

**Comment by dschultzca** [comment]
I was thinking about this a bit further.  What if we add an endian attribute to the <memmodel endian="little"></memmodel> element in the <romid> to globally define the endian of the XML definition.  Then in code if this attribute is set it takes precedence over any endian= attribute in the <table> element of individual tables.
This wold allow the existing definitions to remain as is and would support your requirement.
I don't think I've ever seen a embedded CPU that uses both endians at the same time.

**Comment by rusefi** [comment]
I agree, new optional global default endian attribute would solve the issue of old configs while also allowing new configs to better control endian. Technically per-table endian override could stay while it in fact does not make much sense.

**Comment by dschultzca** [comment]
I've implemented the global endian concept.  If you'd like to test it grab my branch here and test it:
https://github.com/dschultzca/RomRaider/tree/endian
You can enter the attribute `<memmodel endian="little">xxx</memmodel>` in the base definition which will be inherited by any more specific ECU definition using that base.

**Comment by dschultzca** [comment]
Added in commit 9dd637fb82a8865fbce7e8c86e61d6b34ff5d726

**Pull request closed without merging**
