### PR TITLE
Save Fine Course Values when Switching Tables

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
this fixes issue: https://github.com/RomRaider/RomRaider/issues/61

### CODE REVIEW

**Comment by dschultzca** [comment]
How do I test this?

**Comment by GTO2013** [comment]
You have to open two tables and edit the fine or coarse value for table No. 1. In the previous version it will reset after you have clicked on table No.2 and then click on No.1 again. With this commit it will save the fine and course values before switching to the other table and will therefore show the previously entered values after you click on it again.

**Comment by dschultzca** [comment]
For some reason it applies the changed values to tables with similar names, not just the open table, is that the intention?

**Comment by GTO2013** [comment]
This happens if multiple tables use the same scale. I would assume that this is still correct behavior, since the new fine/coarse value should also be correct for other tables with the same scale?

**Comment by dschultzca** [comment]
So then it will apply to all tables using the same scaling even if the tables are not in the same category?

**Comment by GTO2013** [comment]
Yes, if the same scale is referenced it will do that, since the fine course values are saved in the scaling. Do you think this is a problem?

**Comment by dschultzca** [comment]
I guess we'll find out if users notice.

**Pull request merged**
