### PR TITLE
Complete Table Redesign and more

### PR DESCRIPTION
**Pull request by GTO2013**
Hi,
this is a pretty large pull request, but I think it fixes and improves a lot of things:

Changes:
- DataCells that map to the same memory auto-update correctly (#115)
-  See video for above: https://streamable.com/kqkdfp
- Tables can have presets to choose from (The same definition as a switch with "state")
- Tables can be masked (use mask='0F' for example)
- 2DTableMaskableSwitchable removed
- Tables have a default size of 1 now if no size is supplied (#87)
- You can use 1D Tables in definitions now, for RPM limiters for example. No need for a 2D Table anymore (#87)
- Quicksave Button (#123)
- Table description selectable, fixed scrollbar as well (#118)
- Refined logger definition loading if the new definition does not contain old protocol
- Refactored ROM matching into ROM_ID object

The live table updates really were a big project, which is why this commit is so large. I have changed the Editor quite significantly: 

Currently the tables get loaded from the binary and then we loop through all tables in the end and save their values. This has the downside that if you only change a single byte in the entire bin, you still save all tables. To make data updates between tables possible I have changed it to this: Once you make a change to a DataCell, it will instantly update its new value in the binary. It will then inform other DataCells to reload their value from memory. Each DataCell is responsible for its own memory region which it will read and write from.

Saving the file itself does not require looping through all tables any longer technically (saveFile function in ROM Class), but it is still needed for the TableSwitch and BitwiseSwitch tables. We could refactor the TableSwitch into just a different rendering of the Table1D class with hidden DataCells (since presets are now an option), but I stopped there for now. But this could be improved in the future, so the saveFile function would be redundant.

What makes reusability a bit hard is that there is no split between Data and Swing/Visuals. I started to split this better by supplying a DataCell (which only contains pure Data and manages its memory region) and a DataView (which has all the swing stuff). Ideally, this should also be done to the Table classes in my opinion.

I also moved the masking and preset options into the basic table class, so the special Table2DMaskedSwitchable table is now removed, but I think I was the only one using that anyway. That's the only part that's not backwards compatible anymore.

I have tested this on my own files and also had some testers on the BMW discord server. If you find anything that needs changing let me know!

### CODE REVIEW

**Comment by dschultzca** [comment]
I tried your changes and found an issue loading a number of tables.

image
`08:39:15,195 ERROR [SwingWorker-pool-2-thread-1] - Error Populating Table
java.lang.NullPointerException
	at com.romraider.maps.Table1D.populateTable(Table1D.java:90)
	at com.romraider.maps.Table2D.populateTable(Table2D.java:137)
	at com.romraider.maps.Rom.populateTables(Rom.java:201)
	at com.romraider.editor.ecu.OpenImageWorker.doInBackground(ECUEditor.java:743)
	at com.romraider.editor.ecu.OpenImageWorker.doInBackground(ECUEditor.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at javax.swing.SwingWorker.run(SwingWorker.java:316)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)`

I'm using this [ROM](http://www.romraider.com/forum/download/file.php?id=5114) and this [definition](https://www.romraider.com/forum/download/file.php?id=9915).

**Comment by GTO2013** [comment]
This should be fixed now, was just a reference to a label that was null in some cases.

**Comment by dschultzca** [comment]
Looks good.
Can you rebase onto the current master please?

**Comment by GTO2013** [comment]
Sure, it should be rebased now

**Comment by GTO2013** [comment]
Thanks for the merge, could you maybe go through the open issues and close those which are already implemented/fixed? That would make it easier to get an overview of what still needs to be done.

**Pull request merged**
